### ISSUE TITLE
Reduce size of repository

### ISSUE THREAD

**Issue by surajnarwade** [kedgeproject/kedge#362]
We can reduce size of repo by polulating `vendor` directory after cloning the repo.

Current size of repo:

```
$ du -sh kedge/
737M	kedge/
```

After removing vendor,

```
$ du -sh kedge/
87M	kedge/
```

**Comment by containscafeine** [comment]
Is 737M the size when we first clone the repo?

**Comment by kadel** [comment]
If we remove vendor from git, it is not guaranteed that we can build Kedge.

Kedge depends on a lot of libraries (transitively because of Kubernetes an OpenShift). What if some of the libraries are deleted from github? Or tag or commit we depend on is deleted? Then it won't be possible to build Kedge.

By having vendor in git we can always be sure that we can build Kedge regarding what happens with any of the libraries.

**Comment by cdrage** [comment]
Yeah, vendor is required :-1:
