### ISSUE TITLE
Parameterize the ingress host

### ISSUE THREAD

**Issue by pradeepto** [kedgeproject/kedge#41]
This will help if when the configs have to moved from one cluster to another. Think dev to stage to prod workflow.

**Comment by surajssd** [comment]
Ingress should be specifically parameterized because ingress host value is cluster specific. The value will always change with how the cluster is setup. While the case with routes is that we just need to say that we need route and the host is auto populated for us.

The parameterization has to happen in two places one in `services.ports.endpoint` and `ingress.rules.host` to be specific, but if we implement some parameterization technique which is generic enough to work with any field we don't need to care what field we are parameterizing.

We could parameterize it the way openshift does it something, which needs to be discussed.

**Comment by containscafeine** [comment]
@pradeepto does it make more sense for this issue to track parametrization, in general, instead of only ingress host?

**Comment by pradeepto** [comment]
@containscafeine https://github.com/kedgeproject/kedge/issues/224 is in milestone 0.3.0. So, yes ingress bit can be handled there. Keep this open, it can be closed when #224 is closed.

**Comment by cdrage** [comment]
@pradeepto @kadel Can we close this since #224 has been merged?

**Comment by kadel** [comment]
#224 will solve this.

https://github.com/kedgeproject/kedge/issues/491 will improve this further


I think that we can close this, as main problem is solved.
