### ISSUE TITLE
Add support for envFrom for configMaps

### ISSUE THREAD

**Issue by containscafeine** [kedgeproject/kedge#43]
Kubernetes 1.6 release added support for `envFrom`, and example of which can be seen [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-pod-environment-variables).

We see there is a pattern in most/a lot of the Kubernetes deployments that all fields from a Secret and/or a ConfigMap are exposed inside the containers of a pod, so we can leverage this field.

Since, Kubernetes v1.6 is fairly new, we might need to support this field for now in our tooling, and after a while, we can leverage it directly.

This partially resolves the wildcard discussions in #2.

**Comment by surajssd** [comment]
Reduced the scope of this issue from `envFrom` for `secret` and `configMap` both to `configMap` only.

Support for `secret` cannot be implemented right now because there is no way to define `secret` yet, once we have a way to define secret in kapp we can implement that feature as well. The issue about *secret with envFrom* is tracked in https://github.com/surajssd/kapp/issues/85 

Since we populate the envs reading from `configMap` so it is mandatory right now to define `configMap` or `secret` in same file. And since there is no way to define `secret` so scope is reduced.


We can do following (atleast one):

- add support for defining `secret` in the file
- when the tool becomes cluster aware and can query things from cluster we can remove the restriction of defining `secret`/`configmap` in the file itself.
