### ISSUE TITLE
Update examples and associated readmes

### ISSUE THREAD

**Issue by pradeepto** [kedgeproject/kedge#60]
The readmes in the examples are perhaps dated. Update them and also update examples if applicable.

**Comment by cdrage** [comment]
@pradeepto Not too sure if this has been completed with the README update?

**Comment by surajssd** [comment]
Following are outdated:

- [ ] [examples/single_file](https://github.com/kedgeproject/kedge/tree/master/examples/single_file) because there is no README for it, 
- [ ] [root level README of examples](https://github.com/kedgeproject/kedge/tree/master/examples) needs update for new examples that were added

Rest all of them are updated
